<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new User';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('user', array('action' => 'add')));
 $form->prepare();
//
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 ?>
  <table class="table">
 <tr>
     <td>
         <?php  echo $this->formRow($form->get('e_email')); ?>
     </td>
     
 </tr>
  <tr>
     <td>
         <?php  echo $this->formRow($form->get('e_password')); ?>
     </td>
   </tr>  
  <tr>
        <td>
         <?php  echo $this->formRow($form->get('retype_password')); ?>
     </td>
 </tr> 
  <tr>
        <td>
         <?php  echo $this->formRow($form->get('e_type')); ?>
     </td>
 </tr>
 </table>
 
 <?php
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>