<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Edit user';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'user',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 ?>
 <table class="table">
 <tr>
     <td>
         <?php  echo $this->formRow($form->get('email')); ?>
     </td>
     
 </tr>
  <tr>
     <td>
         <?php  echo $this->formRow($form->get('password')); ?>
     </td>
   </tr>  
  <tr>
        <td>
         <?php  echo $this->formRow($form->get('retype_password')); ?>
     </td>
 </tr>
  <tr>
        <td>
         <?php  echo $this->formRow($form->get('type')); ?>
     </td>
 </tr>
 </table>
 <?php
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 